// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://naisvyomguajpwkklkwa.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5haXN2eW9tZ3VhanB3a2tsa3dhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzczMTA1MTYsImV4cCI6MjA5Mjg4NjUxNn0.C_rTxpkr8V_x6vQjE-pYEK_J7RjKHxr1rPcnX7BCg1M";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);